# .github/workflows/testrigor.yml

name: testRigor CI
 
on:

  push:

    branches:

      - main

  workflow_dispatch:
 
jobs:

  run-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v3
 
      - name: Run testRigor script

        run: |

          # Paste the Bash script you copied here,

          # replacing placeholders like {$auth-token} and {$testId}

          # with your GitHub secret variables:

          # ${{ secrets.TR_AUTH_TOKEN }}, ${{ secrets.TR_SUITE_ID }}

 
